name: CI

on:
  push:
    branches:
      - bhabani-basic-brnach
  pull_request:
    branches:
      - bhabani-basic-brnach

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build . -t basic-server-image24:latest

    - name: Run Unit Tests
      run: docker run --rm basic-server-image24:latest npm test

    - name: Start App Service
      run: |
        docker run -d --name basic-server -p 3000:3000 basic-server-image24:latest
        # Give some time for the service to start
        sleep 5

    - name: Run Sanity Tests
      run: |
        curl --fail http://localhost:3000/health

    - name: Run Regression Tests
      run: docker run --rm basic-server-image24:latest npm run regression-tests

    - name: Stop App Service
      run: docker stop basic-server
