name: CI

on:
  push:
    branches:
      - bhabani-basic-brnach
  pull_request:
    branches:
      - bhabani-basic-brnach

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      app:
        image: basic-server-image24:latest
        ports:
          - 3000:3000
        options: >-
          --health-cmd="curl --fail http://localhost:3000/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build . -t basic-server-image24:latest

    - name: Run Unit Tests
      run: docker run --rm basic-server-image24:latest npm test

    - name: Run Sanity Tests
      run: |
        # Replace with your actual sanity test command
        docker run --rm basic-server-image24:latest curl -f http://localhost:3000/health

    - name: Run Regression Tests
      run: docker run --rm basic-server-image24:latest npm run regression-tests
